-- Migration 068: Seed Product Categories from ShopVOX
INSERT INTO public.product_categories (organization_id, name, product_type_id)
SELECT o.id, v.name, pt.id
FROM public.organizations o
CROSS JOIN (VALUES
  ('3D Acrylic Lit Signs','Illuminated Signs'),
  ('3D Lit Signs','Illuminated Signs'),
  ('Accessories','Material Resale'),
  ('Acrylic Signs','Signs / Large Format Printing'),
  ('ADA Signs','Signs / Large Format Printing'),
  ('AI - Receptionist','Digital Marketing'),
  ('Assembly','Signs / Large Format Printing'),
  ('Backlit','Signs / Large Format Printing'),
  ('Backlit- Digital Vinyl Print','Illuminated Signs'),
  ('Backlit Faces','Signs / Large Format Printing'),
  ('Backlit- Flexface','Illuminated Signs'),
  ('Backlit- Rigid Faces','Illuminated Signs'),
  ('Backlit Vinyl Prints','Signs / Large Format Printing'),
  ('Banner- Regular / Mesh / Anti-curl / Block-out','Signs / Large Format Printing'),
  ('Billboards','Signs / Large Format Printing'),
  ('Booklets','Commercial Printing'),
  ('Bookmarkers','Commercial Printing'),
  ('Brochures','Commercial Printing'),
  ('Bumper Stickers','Signs / Large Format Printing'),
  ('Business Cards','Commercial Printing'),
  ('Buttons','Commercial Printing'),
  ('Canvas','Signs / Large Format Printing'),
  ('Carboard Signs','Signs / Large Format Printing'),
  ('Carved/ Sandblast Signs','Signs / Large Format Printing'),
  ('Channel Letter Materials','Material Resale'),
  ('Clear Film Prints','Signs / Large Format Printing'),
  ('Coasters- Digitally Printed','Promotional / Outsource'),
  ('Coasters- Hot Stamped','Promotional / Outsource'),
  ('Commercial Lamination','Commercial Printing'),
  ('Consulting','Digital Marketing'),
  ('Construction Signs','Signs / Large Format Printing'),
  ('Contract Pricing','Signs / Large Format Printing'),
  ('Copies','Commercial Printing'),
  ('Coroplast Signs','Signs / Large Format Printing'),
  ('Custom','Signs / Large Format Printing'),
  ('Custom Display','Signs / Large Format Printing'),
  ('Decals','Signs / Large Format Printing'),
  ('Decals/ Stickers','Promotional / Outsource'),
  ('Desk Name Plates','Signs / Large Format Printing'),
  ('Digital LED Signs','Illuminated Signs'),
  ('Digital Prints','Signs / Large Format Printing'),
  ('Digital Vinyl Prints','Signs / Large Format Printing'),
  ('Dimensional 3D Signs','Signs / Large Format Printing'),
  ('Dimensional Letters','Illuminated Signs'),
  ('Displays','Signs / Large Format Printing'),
  ('Domain Name','Digital Marketing'),
  ('Door Hangers','Commercial Printing'),
  ('Dry Erase Board','Signs / Large Format Printing'),
  ('Electrical Materials','Material Resale'),
  ('Envelopes','Commercial Printing'),
  ('Event Banners','Promotional / Outsource'),
  ('Event Item','Promotional / Outsource'),
  ('Event Signage','Signs / Large Format Printing'),
  ('Exterior Signage','Illuminated Signs'),
  ('Exterior Signage','Signs / Large Format Printing'),
  ('Fabric','Signs / Large Format Printing'),
  ('Fabric Backlit Print','Signs / Large Format Printing'),
  ('Fabric Front-lit Print','Signs / Large Format Printing'),
  ('Fabrication Materials','Material Resale'),
  ('Falconboard Signs','Signs / Large Format Printing'),
  ('Feather Flags','Signs / Large Format Printing'),
  ('Fees/Charges','Signs / Large Format Printing'),
  ('Finishing - Binding','Commercial Printing'),
  ('Finishing - Commercial Printing','Commercial Printing'),
  ('Fire Pac','Signs / Large Format Printing'),
  ('Flag Hardware & Accessories','Promotional / Outsource'),
  ('Flags','Promotional / Outsource'),
  ('Flags','Signs / Large Format Printing'),
  ('Flat Lit Signs','Illuminated Signs'),
  ('Flat Signs','Illuminated Signs'),
  ('Floor Graphics','Signs / Large Format Printing'),
  ('Floor Standups','Signs / Large Format Printing'),
  ('Flyers','Commercial Printing'),
  ('Foamboard Signs','Signs / Large Format Printing'),
  ('Forms','Commercial Printing'),
  ('Frames & Stakes','Signs / Large Format Printing'),
  ('Frontlit','Illuminated Signs'),
  ('Gift Certificates','Commercial Printing'),
  ('Golden Products - Pro','Commercial Printing'),
  ('Google My Business','Digital Marketing'),
  ('Graphic Design','Branding'),
  ('Hang Tags','Commercial Printing'),
  ('Hardware / Accessories','Signs / Large Format Printing'),
  ('Hosting','Digital Marketing'),
  ('Hosting & Security','Digital Marketing'),
  ('Indoor Banners','Signs / Large Format Printing'),
  ('Installation','Illuminated Signs'),
  ('Installation','Signs / Large Format Printing'),
  ('Interior & Exterior','Signs / Large Format Printing'),
  ('Interior Decor','Signs / Large Format Printing'),
  ('Interior Signage','Illuminated Signs'),
  ('Interior Signage','Signs / Large Format Printing'),
  ('Labels','Commercial Printing'),
  ('Labels & Decals','Signs / Large Format Printing'),
  ('Large Format Asset','Asset'),
  ('LED Neon Borders','Illuminated Signs'),
  ('LED Neon Signs','Illuminated Signs'),
  ('Letterheads','Commercial Printing'),
  ('Lightboxes','Illuminated Signs'),
  ('Logo','Branding'),
  ('Magnets','Promotional / Outsource'),
  ('Magnets','Signs / Large Format Printing'),
  ('Menus','Commercial Printing'),
  ('Metal Signs','Signs / Large Format Printing'),
  ('Misc. Fees','Material Resale'),
  ('Misc. Fees','Signs / Large Format Printing'),
  ('Monument Sign','Illuminated Signs'),
  ('Name Tags / Id Badges','Signs / Large Format Printing'),
  ('Neon Signs','Illuminated Signs'),
  ('Notebooks','Commercial Printing'),
  ('Notecards','Commercial Printing'),
  ('Notepads','Commercial Printing'),
  ('Office Name Plates','Illuminated Signs'),
  ('Outdoor Banners','Signs / Large Format Printing'),
  ('Paid Ads Management','Digital Marketing'),
  ('Paper Coasters','Commercial Printing'),
  ('Paper Prints','Signs / Large Format Printing'),
  ('Parking Signs','Signs / Large Format Printing'),
  ('Pennants','Signs / Large Format Printing'),
  ('Permits- Lite / Outdoor Signage','Illuminated Signs'),
  ('Permit','Signs / Large Format Printing'),
  ('Photography','Digital Marketing'),
  ('Pole Banners','Signs / Large Format Printing'),
  ('Political','Commercial Printing'),
  ('Political','Direct Mail'),
  ('POP Display','Signs / Large Format Printing'),
  ('Pop Up Display','Signs / Large Format Printing'),
  ('Postcards','Direct Mail'),
  ('Postage','Direct Mail'),
  ('Post & Panel Signs- Aluminum','Illuminated Signs'),
  ('Post & Panel Signs- Steel','Illuminated Signs'),
  ('Post & Panel Signs- Wood','Illuminated Signs'),
  ('Posters','Signs / Large Format Printing'),
  ('Print & Cut','Signs / Large Format Printing'),
  ('Processing & Listing','Direct Mail'),
  ('Processing Fees','Promotional / Outsource'),
  ('Promotional','Signs / Large Format Printing'),
  ('Promotional Items','Promotional / Outsource'),
  ('Pylon Sign','Illuminated Signs'),
  ('Racing Flags','Signs / Large Format Printing'),
  ('Ratchet Straps','Signs / Large Format Printing'),
  ('Real Estate Signs','Signs / Large Format Printing'),
  ('Removal','Illuminated Signs'),
  ('Repairs','Illuminated Signs'),
  ('Retractable Banners','Signs / Large Format Printing'),
  ('Retractable Banner','Signs / Large Format Printing'),
  ('Riders','Illuminated Signs'),
  ('Rigid Signs- Direct Print','Signs / Large Format Printing'),
  ('Rigid Signs- Direct Printing','Promotional / Outsource'),
  ('Roll Materials','Material Resale'),
  ('Routed Substrate with Digital','Signs / Large Format Printing'),
  ('Routed Substrates','Signs / Large Format Printing'),
  ('Sign Cabinets','Illuminated Signs'),
  ('Sign Faces','Illuminated Signs'),
  ('Site Survey','Illuminated Signs'),
  ('Social Media','Digital Marketing'),
  ('Stickers','Signs / Large Format Printing'),
  ('Substrates','Material Resale'),
  ('Table Cover- Fitted','Signs / Large Format Printing'),
  ('Table Cover- Stretched','Signs / Large Format Printing'),
  ('Table Runner','Signs / Large Format Printing'),
  ('Table Throw','Signs / Large Format Printing'),
  ('Table Throws','Signs / Large Format Printing'),
  ('Tent','Signs / Large Format Printing'),
  ('Trade Show','Signs / Large Format Printing'),
  ('Translucent','Illuminated Signs'),
  ('Vacuum Formed Faces','Illuminated Signs'),
  ('Vehicle Wraps','Signs / Large Format Printing'),
  ('Vinyl Graphics','Signs / Large Format Printing'),
  ('Wayfinding/ Directional Signs','Illuminated Signs'),
  ('Wayfinding/ Directional Signs','Signs / Large Format Printing'),
  ('Website Design & Build Standard','Digital Marketing'),
  ('Window Decals','Signs / Large Format Printing'),
  ('Wiring Run','Illuminated Signs'),
  ('Wood Signs','Signs / Large Format Printing'),
  ('Wristbands','Promotional / Outsource'),
  ('Yard Signs','Signs / Large Format Printing')
) AS v(name, type_name)
JOIN public.product_types pt ON pt.organization_id = o.id AND pt.name = v.type_name
ON CONFLICT DO NOTHING;
