-- ============================================================
-- Migration 111: promo_codes
-- Applied: 2026-08-05
-- ============================================================
--
-- Settings -> Promo Codes. PrintOS's equivalent of ShopVOX's Discount
-- Codes. Forward-looking infrastructure for a future customer
-- self-checkout / Customer Portal ordering flow -- not wired into the
-- current manual quote flow, and no redemption/usage-tracking exists
-- yet since there's no checkout to attach it to. `limit_of_using` is
-- stored (matching ShopVOX's field) but nothing enforces it today.
--
-- `code` is auto-generated by the app (format "WXXA-JL1D-LFVQ", see
-- generatePromoCode() in actions-sr.ts) but editable, matching
-- ShopVOX's own edit form (auto-filled, not required to be typed by
-- hand). Unique per org so two codes can't collide at redemption time
-- whenever that's built.

CREATE TABLE IF NOT EXISTS promo_codes (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name                  text NOT NULL,
  code                  text NOT NULL,
  discount_type         text NOT NULL DEFAULT 'Percentage',
  value                 numeric(10,2) NOT NULL DEFAULT 0,
  minimum_requirement   numeric(10,2),
  limit_of_using        integer NOT NULL DEFAULT 0,
  valid_from            date,
  valid_to              date,
  is_active             boolean NOT NULL DEFAULT true,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, code)
);

-- Grants (required)
grant select                         on public.promo_codes to anon;
grant select, insert, update, delete on public.promo_codes to authenticated;
grant select, insert, update, delete on public.promo_codes to service_role;

-- RLS
ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "promo_codes_select" ON promo_codes;
CREATE POLICY "promo_codes_select" ON promo_codes FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "promo_codes_insert" ON promo_codes;
CREATE POLICY "promo_codes_insert" ON promo_codes FOR INSERT
  WITH CHECK (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid() AND role IN ('owner', 'admin')));

DROP POLICY IF EXISTS "promo_codes_update" ON promo_codes;
CREATE POLICY "promo_codes_update" ON promo_codes FOR UPDATE
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid() AND role IN ('owner', 'admin')));

DROP POLICY IF EXISTS "promo_codes_delete" ON promo_codes;
CREATE POLICY "promo_codes_delete" ON promo_codes FOR DELETE
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid() AND role IN ('owner', 'admin')));

-- Indexes
CREATE INDEX IF NOT EXISTS idx_promo_codes_org ON promo_codes(organization_id);
